# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Parent'),
        ),
    ]
